pulling in a logstash formatter for structured log output
project-receptor/python-receptor pull request #142
Opened 2020-02-24 17:22 UTC by jhjaggars

The rationale is to add structured logging output so that users can integrate the logging into aggregation systems more easily.  This also allows more context to be added to logs for later automation.

Todo for this PR is more robust configuration for logging in __main__.

Signed-off-by: Jesse Jaggars <jjaggars@redhat.com>

2020-02-25 12:11 UTC, matburt requested changes

2020-02-25 12:11 UTC, matburt commented on receptor/config.py
> +            default_value='verbose',
`verbose` sounds a little incorrect here, because it doesn't *really* describe the format as much as it does the volume of messages, which is more related to `debug` logging.

2020-02-26 17:49 UTC, jhjaggars commented on receptor/config.py
> +            default_value='verbose',
That's the name of the current formatter fwiw.  What do you think of something like `plain` or `simple`?

2020-02-26 18:57 UTC, matburt commented on receptor/config.py
> +            default_value='verbose',
simple sounds good

2020-03-12 15:56 UTC, matburt approved these changes

2020-03-12 16:05 UTC, merged