Add ws_extra_header option
project-receptor/python-receptor pull request #161
Opened 2020-03-09 22:21 UTC by ghjm

This adds the `--ws_extra_header` command line and config file option.  When used as follows:
```
receptor ping foo --peer ws://localhost:1234 --ws_extra_header=x-special-auth:supersecret --ws_extra_header=foo:bar
```
this will cause the Receptor client to include `x-special-auth` and `foo` HTTP headers on initial connection to its peer.

2020-03-10 12:44 UTC, jhjaggars requested changes

2020-03-10 12:44 UTC, jhjaggars commented on receptor/connection/ws.py
> +        extra_headers = [(key.strip(), value.strip()) for key, sep, value in
I'd prefer to parse the command line outside of this function so that callers don't have to send in formatted strings for `connect`.

2020-03-10 12:44 UTC, jhjaggars commented on receptor/connection/ws.py
> +    print("------------------------------ In connect --------------------------")
Maybe switch this for a debug log message?

2020-03-10 14:34 UTC, ghjm commented on receptor/connection/ws.py
> +    print("------------------------------ In connect --------------------------")
Oh jeez, this was debugging code that slipped in

2020-03-11 13:28 UTC, ghjm commented on receptor/connection/ws.py
> +        extra_headers = [(key.strip(), value.strip()) for key, sep, value in
Yep, you're right, I was just trying to avoid messing with config.py.  But that's the right place to put this.  Fixed.

2020-03-11 13:28 UTC, ghjm commented on receptor/connection/ws.py
> +    print("------------------------------ In connect --------------------------")
Fixed

2020-03-11 13:39 UTC, jhjaggars approved these changes

2020-03-11 14:17 UTC, merged