Update Dockerfile
project-receptor/python-receptor pull request #36
Opened 2019-10-25 13:36 UTC by elyezer

Do the following:

* Use Fedora 30 as the base image
* Install receptor from source rather than wheel
* Set /var/lib/receptor as the home directory for receptor

2019-10-25 18:17 UTC, matburt requested changes
I think we're going to need to find a better way to propogate the code into the image than adding the dev directory.

2019-10-25 18:17 UTC, matburt commented on packaging/docker/Dockerfile
> +ADD . /receptor
I definitely like having the ability to publish into this but I'm not sure this is the right approach since it leaves the entire source tree IN the image which will not make this very distributable.

2019-10-25 20:46 UTC, elyezer commented on packaging/docker/Dockerfile
> +ADD . /receptor
That is a good point and was expecting to hear more about it. My current thought is to `rm -rf /receptor` after getting it installed. I will do some research and see if there is a better way.

In the mean time, do you think the `rm -rf /receptor` suffice your concern?

2019-10-28 14:06 UTC, elyezer commented on packaging/docker/Dockerfile
> +ADD . /receptor
PR is updated

2019-10-28 14:09 UTC, elyezer commented
@matburt I've updated the PR to remove the `/receptor` from the container file system. I saw about multi-stage build (https://docs.docker.com/develop/develop-images/multistage-build/) and that may allow us to build the receptor wheel and get it installed. I will continue taking a look how we could improve the container image and will send a PR later if I found something better to use.

2019-10-28 18:25 UTC, elyezer commented
I found that running `dnf update` is adding about `80MB` to the image but I think that is advised to ensure everything is up to date and with all the security fixes in. Any concerns/suggestions about that?

2019-10-29 18:53 UTC, matburt commented
The problem is you're adding the *entire* dev directory to the image, which would include the .git directory. The goal of this dockerfile is to generate a functional production image of Receptor so we need to generate a whl or something and install it into this.

2019-10-29 18:53 UTC, matburt commented
https://github.com/project-receptor/receptor/pull/36/files#diff-f311f62c5fdfdc737647797c7afac2beR3

Don't do this

2019-10-30 17:29 UTC, elyezer commented
@matburt I was adding the entire git repo and then removing afterwards but I get your concern. I've update the PR to add the `whl` generated by `make dist` and then installs from it.

Also I've removed the dnf update which is generating a smaller image. I can add it back in case anyone things that is important to get the most updated RPM packages.

2019-10-30 20:16 UTC, matburt commented
We probably *do* need that DNF  update... what's the size delta after that?

2019-10-31 05:24 UTC, elyezer commented
The image was updated recently (about an hour ago) and therefore there is no difference anymore, it was 80MB more before.

See below for the generated image size without the `dnf update`:

```
receptor             latest              b570cf745c20        12 seconds ago      255MB
```

And with the `dnf update`:

```
receptor             latest              66c36ab87aad        3 seconds ago       255MB
```

I'll update the PR with the `dnf update` in place.

2019-10-31 05:27 UTC, elyezer commented
Another change that I've made was to use the recent released Fedora 31 image and that is giving a smaller image:

```
receptor             latest              8bd93f5eca9c        About a minute ago   220MB
```

2019-11-01 16:08 UTC, matburt approved these changes
This looks good. We may still need to tweak the mechanism for getting the right dist into the image but this is good under a `make clean && make image` workflow.

2019-11-01 16:08 UTC, merged