WIP: incoming buffer is now async
project-receptor/python-receptor pull request #40
Opened 2019-11-12 16:02 UTC by jhjaggars

2019-11-12 16:27 UTC, matburt commented on receptor/protocol.py
> +            self.q.put_nowait(chunk)
What's the logic behind `put_nowait()` here?

2019-11-13 02:24 UTC, jhjaggars commented on receptor/protocol.py
> +            self.q.put_nowait(chunk)
2 reasons.
1. I never expect this write to block since the queue is unbounded
2. The caller of add executes in a blocking context

2019-11-14 15:01 UTC, matburt requested changes
This is probably just a small thing.

2019-11-14 15:01 UTC, matburt commented on receptor/protocol.py
> -        while not self.greeted:
If we're not checking `self.greeted` here then we can just throw this bool away entirely?

2019-11-14 20:33 UTC, matburt commented on receptor/protocol.py
> +                logger.debug("about to wait for a message")
I strongly prefer the verbage `fixin' to`

2019-11-14 20:33 UTC, matburt commented on receptor/protocol.py
> -                logger.exception("Receptor Buffer Read Error: {}".format(e))
👍

2019-11-18 15:20 UTC, matburt reviewed
We were chatting about making sure we can handle corrupt/bad manifests this might lead to that.

2019-11-18 15:20 UTC, matburt commented on receptor/buffers/file.py
> +            except FileNotFoundError:
I bet we can get other exceptions here too like `PermissionError`

2019-11-18 15:38 UTC, jhjaggars commented on receptor/buffers/file.py
> +            except FileNotFoundError:
How would you want to handle an error like that?

Do you think we should just handle every error this step by skipping? (maybe logging that we are skipping?)

2019-11-18 18:04 UTC, matburt commented on receptor/buffers/file.py
> +            except FileNotFoundError:
If we have a permission denied then we have a pretty critical problem that probably can't be resolved holistically by skipping. Part of me thinks we'd have to shut the whole service down in that scenario.

2019-11-18 18:49 UTC, jhjaggars commented on receptor/buffers/file.py
> +            except FileNotFoundError:
I've added special handling to the consumer of the buffer to catch other errors and handle them appropriately.  More work to be done in the future though.

2019-11-18 18:51 UTC, matburt approved these changes

2019-11-18 18:52 UTC, merged